# Generated by Django 4.2.1 on 2023-06-02 20:16

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('news', '0002_alter_article_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LMSUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address')),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], max_length=30)),
                ('group', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.group')),
            ],
            options={
                'verbose_name': 'lms_user',
                'verbose_name_plural': 'lms_users',
                'db_table': 'first_app_lms_users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
